INSERT INTO DRONE (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('D1001','LIGHTWEIGHT',500,100,'IDLE');
INSERT INTO DRONE (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('D1002','MIDDLEWEIGHT',750,100,'IDLE');
INSERT INTO DRONE (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('D1003','CRUISERWEIGHT',900,100,'IDLE');
INSERT INTO DRONE (SERIAL_NUMBER, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('D1004','HEAVYWEIGHT',1000,100,'IDLE');


INSERT INTO MEDICATION (CODE, NAME, WEIGHT, MED_PHOTO) VALUES ('M-1001','PARACETAMOL',100,'PARACETAMOL.JPG');
INSERT INTO MEDICATION (CODE, NAME, WEIGHT, MED_PHOTO) VALUES ('M-1002','COUGH SYRUP',250,'PARACETAMOL.JPG');
INSERT INTO MEDICATION (CODE, NAME, WEIGHT, MED_PHOTO) VALUES ('M-1003','MEDICINE KIT',500,'PARACETAMOL.JPG');
INSERT INTO MEDICATION (CODE, NAME, WEIGHT, MED_PHOTO) VALUES ('M-1004','IV Fluid',250,'PARACETAMOL.JPG');