CREATE TABLE DRONE(
	SERIAL_NUMBER VARCHAR(100) PRIMARY KEY,
	MODEL VARCHAR(20) NOT NULL,
	WEIGHT_LIMIT INTEGER NOT NULL,
	BATTERY_CAPACITY INTEGER NOT NULL,
	STATE VARCHAR(20) NOT NULL
);

CREATE TABLE MEDICATION(
	CODE VARCHAR(100) PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	WEIGHT INTEGER NOT NULL,
	MED_PHOTO VARCHAR(100)
);

CREATE TABLE DRONE_LOAD(
	DRONE_SERIAL VARCHAR(100) NOT NULL,
	MEDICATION_CODE VARCHAR(100) NOT NULL,
	WEIGHT INTEGER NOT NULL,
	FOREIGN KEY (DRONE_SERIAL) REFERENCES DRONE(SERIAL_NUMBER),
	FOREIGN KEY (MEDICATION_CODE) REFERENCES MEDICATION(CODE)
);