CREATE TABLE DRONE(
	SERIAL_NUMBER VARCHAR(100) PRIMARY KEY,
	MODEL VARCHAR(20) NOT NULL,
	WEIGHT_LIMIT INTEGER NOT NULL,
	BATTERY_CAPACITY INTEGER NOT NULL,
	STATE VARCHAR(20) NOT NULL
);

CREATE TABLE MEDICATION(
	CODE VARCHAR(100) PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	WEIGHT INTEGER NOT NULL,
	MED_PHOTO VARCHAR(100)
);